name: action release pipeline
on:
  push:
    branchs:
      - 'main'
  workflow_dispatch:    
jobs:
 test:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - name: test my action
    uses: ./
    with:
      message: "Hello $GITHUB_REPOSITORY_OWNER From GH Actions workflow"

